# https://github.com/ondrejbartas/sidekiq-cron
# use https://crontab.guru/ to validate
# validations for this file exist in /spec/configs/schedule_spec.rb


# executed At every 5th minute..
trigger_scheduled_items_job:
  cron: '*/5 * * * *'
  class: 'TriggerScheduledItemsJob'
  queue: scheduled_jobs

# executed At every minute..
trigger_imap_email_inboxes_job:
  cron: '*/1 * * * *'
  class: 'Inboxes::FetchImapEmailInboxesJob'
  queue: scheduled_jobs

# executed daily at 00:00.
trigger_sync_channel_token_expiry_date:
  cron: '0 0 * * *'
  class: 'Channels::Whatsapp::TokenSyncSchedulerJob'
  queue: scheduled_jobs
